// Shared inline styles for the DevPanel family. Keeps styling self-contained
// so dev tools don't drag in global CSS or coupling to the main app theme.

import type { CSSProperties } from 'react';

export const devStyles: Record<string, CSSProperties> = {
  panel: {
    position: 'fixed',
    right: 16,
    top: 16,
    width: 360,
    maxHeight: 'calc(100vh - 32px)',
    overflowY: 'auto',
    background: 'rgba(10, 14, 20, 0.94)',
    color: '#e6edf7',
    fontFamily: "'SF Mono', ui-monospace, Menlo, Consolas, monospace",
    fontSize: 12,
    borderRadius: 8,
    border: '1px solid #2c3442',
    boxShadow: '0 8px 24px rgba(0,0,0,0.45)',
    zIndex: 9999,
    padding: 12,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    borderBottom: '1px solid #2c3442',
    paddingBottom: 6,
  },
  title: {
    fontSize: 13,
    fontWeight: 600,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  tabs: {
    display: 'flex',
    gap: 4,
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  tab: {
    padding: '4px 8px',
    background: '#1b2230',
    border: '1px solid #2c3442',
    borderRadius: 4,
    cursor: 'pointer',
    color: '#bac6d9',
    fontSize: 11,
  },
  tabActive: {
    background: '#2a4a6b',
    borderColor: '#3d6ba0',
    color: '#fff',
  },
  section: {
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 11,
    color: '#8aa4c4',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '2px 0',
  },
  button: {
    padding: '4px 10px',
    background: '#2a4a6b',
    border: '1px solid #3d6ba0',
    borderRadius: 4,
    color: '#fff',
    cursor: 'pointer',
    fontSize: 11,
    marginRight: 4,
    marginTop: 2,
  },
  input: {
    background: '#0c1118',
    border: '1px solid #2c3442',
    color: '#e6edf7',
    borderRadius: 3,
    padding: '2px 6px',
    fontSize: 11,
    fontFamily: 'inherit',
    width: '100%',
    boxSizing: 'border-box',
  },
  pre: {
    background: '#0c1118',
    padding: 6,
    borderRadius: 4,
    fontSize: 10,
    whiteSpace: 'pre-wrap' as const,
    wordBreak: 'break-all' as const,
    maxHeight: 180,
    overflowY: 'auto',
  },
  warn: { color: '#f5a623' },
  good: { color: '#7bd88f' },
  muted: { color: '#6f7f97' },
};
